language: python
python:
   - '3.5'
   - '2.7'
   - '3.4'
   - '3.5'
   - '3.6'

install:
    - pip install tox
    - pip install coveralls

script: tox

after_success:
  - coveralls

services:
  - redis-server
